---
.travis.yml:
  script: "\"bundle exec rake spec SPEC_OPTS='--format documentation'\""
  rvms:
    - 1.8.7
    - 1.9.3
    - 2.0.0
  excludes:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
  env_matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
Gemfile:
  required:
    - gem: rake
    - gem: rspec-puppet
    - gem: puppetlabs_spec_helper
    - gem: serverspec
    - gem: puppet-lint
    - gem: beaker
    - gem: beaker-rspec
