---
language: ruby
bundler_args: --without development
script: <%= @configs['script'] %>
matrix:
  fast_finish: true
  include:
<% @configs['includes'].each do |include| -%>
  - rvm: <%= include['rvm'] %>
    env: <%= include['env'] %>
<% end -%>
<% if @configs['extras'] -%>
<%   @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
    env: <%= extra['env'] %>
<%   end -%>
<% end -%>
notifications:
  email: false
